name: Node3

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Start server
      run: |
        sudo npm start &
        sleep 6 # Give server some time to start
    - name: Check if server is running
      run: |
        curl --fail http://localhost:80 || exit 1
    - name: Run tests
      run: npm run test